### ISSUE TITLE
Upgrade reqwest to v0.12

### ISSUE THREAD

**Issue by sigoden** [maoertel/diqwest#17]
Hello, thanks for this amazing project.

[Reqwest v0.12](https://github.com/seanmonstar/reqwest/releases/tag/v0.12.0) upgrades hyper, http and http-body to v1. It seems like a minor version update, but its impact is huge.

[Reqwest v0.11](https://github.com/seanmonstar/reqwest/releases/tag/v0.11.0) released on January 6, 2021. It's been a long time since reqwest v0.11 to v0.12.

Can you update the `reqwest` dependency to v0.12 and release a new version?

**Comment by maoertel** [comment]
Hey sigoden,

yes, will work on that this week and update the crate. :v:

**Comment by maoertel** [comment]
Solved by #18
